apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-deployment
  labels: 
    app: node
spec:
  replicas: 10
  selector:
    matchLabels:
      app: node
  template:
    metadata:
      labels:
        app: node
    spec:
      containers:
      - name: node-container
<<<<<<< HEAD
        image: harper1105/nodeapi:latest
=======
        image: stratcastor/nodeapi:latest
>>>>>>> 96c433b2a8b9d7e1de040cefb070e8c34a00d23e
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: node-service
spec:
  type: ClusterIP
  selector:
    app: node
  ports:
  - protocol: TCP
    port: 8080  
<<<<<<< HEAD
    targetPort: 8080
=======
    targetPort: 8080
>>>>>>> 96c433b2a8b9d7e1de040cefb070e8c34a00d23e
